# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  #  scrape_timeout: 15s
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 177.55.119.91:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090', 'localhost:9487']
      labels:
        service: prometheus
        instance: prometheus

  - job_name: 'APP'
    #    scrape_interval: 5s
    static_configs:
      - targets: ['187.84.225.50:5000']
        labels:
          service: 'APP'
          instance: 'ubapp01'
